export const MOCK_ORDERS = [
	{
		id: "ORD-4821",
		customerName: "Rahul Mehta",
		phone: "+91 98765 43210",
		fileName: "Semester_Notes_Final.pdf",
		pages: 18,
		copies: 3,
		color: "B&W (Economy)",
		paperSize: "A4",
		binding: "Spiral Binding",
		notes: "Double sided please.",
		status: "new",
		timeAgo: "2 min ago",
		total: 270,
	},
	{
		id: "ORD-4819",
		customerName: "Priya Nair",
		phone: "+91 91234 56789",
		fileName: "Company_Brochure_v3.pdf",
		pages: 8,
		copies: 1,
		color: "Color (CMYK)",
		paperSize: "A3",
		binding: "None",
		notes: "Matte finish if possible.",
		status: "printing",
		timeAgo: "14 min ago",
		total: 120,
	},
	{
		id: "ORD-4815",
		customerName: "Arjun Desai",
		phone: "+91 99887 76655",
		fileName: "Thesis_Chapter4.pdf",
		pages: 42,
		copies: 2,
		color: "B&W (Economy)",
		paperSize: "A4",
		binding: "Hardbound",
		notes: "Need by 5 PM today.",
		status: "ready",
		timeAgo: "38 min ago",
		total: 420,
	},
	{
		id: "ORD-4809",
		customerName: "Sneha Kulkarni",
		phone: "+91 90909 12121",
		fileName: "Resume_2026.pdf",
		pages: 2,
		copies: 5,
		color: "Color (CMYK)",
		paperSize: "A4",
		binding: "None",
		notes: "No special instructions",
		status: "completed",
		timeAgo: "1 hr ago",
		total: 150,
	},
];

export const MOCK_PRICING_PLANS = [
	{
		name: "Starter",
		badge: "For single counters",
		description: "Everything a single-shop owner needs to go digital.",
		priceMonthly: "₹499",
		popular: false,
		features: [
			"1 shop QR code",
			"Unlimited orders",
			"Live dashboard sync",
			"Email support",
		],
	},
	{
		name: "Growth",
		badge: "Most popular",
		description: "For busy shops with multiple counters or staff.",
		priceMonthly: "₹999",
		popular: true,
		features: [
			"Up to 3 shop QR codes",
			"Unlimited orders",
			"Live dashboard sync",
			"SMS notifications to customers",
			"Priority support",
		],
	},
	{
		name: "Chain",
		badge: "For multi-branch shops",
		description: "Manage several print outlets from one account.",
		priceMonthly: "₹2,499",
		popular: false,
		features: [
			"Unlimited shop QR codes",
			"Unlimited orders",
			"Centralized owner dashboard",
			"SMS notifications",
			"Dedicated support",
		],
	},
];

export const MOCK_TESTIMONIALS = [
	{
		quote: "We used to lose track of WhatsApp orders constantly. Now every order lands straight on the counter screen — no more scrolling through chats.",
		rating: 5,
		author: "Vikram Gupta",
		role: "Owner",
		location: "Gupta Xerox & Press, Pune",
	},
	{
		quote: "Students scan, upload, and pick copies themselves. My staff just prints. It's cut our counter wait time in half.",
		rating: 5,
		author: "Anita Sharma",
		role: "Manager",
		location: "Campus Print Point, Mumbai",
	},
	{
		quote: "The dashboard alone was worth switching for. I can finally see what's pending without asking my staff to check three different phones.",
		rating: 4,
		author: "Rohan Iyer",
		role: "Owner",
		location: "Iyer Digital Prints, Bangalore",
	},
];

export const MOCK_FAQ = [
	{
		question: "Do customers need to download an app?",
		answer: "No. Customers scan the QR code with their phone's camera and it opens directly in their browser — no app install required.",
	},
	{
		question: "What file types are supported?",
		answer: "Currently PDF only. Support for images and Word/PowerPoint documents is planned for a future release.",
	},
	{
		question: "How is my order data kept private from other shops?",
		answer: "Each shop's orders are fully isolated at the database level — one shop owner can never see or access another shop's orders, even by guessing an order ID.",
	},
	{
		question: "What happens to uploaded files after printing?",
		answer: "Files are automatically deleted from storage after a configurable expiry window, so nothing lingers indefinitely.",
	},
];
