-- AlterTable
ALTER TABLE "OrderFile" ADD COLUMN     "doubleSided" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "pageCount" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Shop" ADD COLUMN     "bwPrice" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN     "colorPrice" DOUBLE PRECISION NOT NULL DEFAULT 10;
